# Generated by Django 3.2.3 on 2021-05-17 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task31'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task31',
            old_name='text',
            new_name='text1',
        ),
    ]
