# Generated by Django 3.2.3 on 2021-05-19 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210519_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books_data',
            old_name='tittle',
            new_name='title',
        ),
    ]
